documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - 'README.md'
          - 'CONTRIBUTING.md'

test:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**/*'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'

core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/frameworks/common/**/*'
          - 'src/operations/**/*'
          - 'src/index.ts'

express:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/frameworks/express/**/*'

fastify:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/frameworks/fastify/**/*'

koa:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/frameworks/koa/**/*'
